# Generated by Django 3.0.5 on 2020-04-28 19:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('Last_Name', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('First_NameF', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('Last_NameF', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('Age', models.IntegerField()),
                ('Date_of_Birth', models.DateField()),
                ('Gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other')], max_length=6)),
                ('Experience', models.CharField(max_length=20)),
                ('Qualify', models.CharField(choices=[{'PHD', 'phd'}, {'Master', 'master'}, {'bachlor', 'Bachlor'}], max_length=10)),
                ('Speclization', models.CharField(choices=[{'please select', 'Please Select'}, {'Networking', 'networking'}, {'database', 'Database'}, {'programming', 'Programming'}], max_length=30)),
                ('Image', models.ImageField(upload_to='')),
                ('cv', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('Last_Name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('Father_Name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('Email', models.EmailField(max_length=254, verbose_name='Email')),
                ('Domicile', models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('Age', models.IntegerField()),
                ('Date_of_Birth', models.DateField()),
                ('Gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other')], max_length=6)),
                ('Phone_no', models.IntegerField()),
                ('Land_Line', models.IntegerField()),
                ('MatricTotal', models.IntegerField()),
                ('MatricObtain', models.IntegerField()),
                ('MatricSubject', models.CharField(max_length=50)),
                ('MatricPercentage', models.FloatField(default=0.0)),
                ('MatricGrades', models.CharField(max_length=5, null=True)),
                ('MatricYear', models.CharField(max_length=20)),
                ('IntermediateTotal', models.IntegerField()),
                ('IntermediateObtain', models.IntegerField()),
                ('IntermediateSubject', models.CharField(max_length=50)),
                ('IntermediatePercentage', models.FloatField(default='0.0')),
                ('IntermediateGrades', models.CharField(max_length=5, null=True)),
                ('IntermediateYear', models.CharField(max_length=20)),
                ('GraduationTotal', models.IntegerField()),
                ('GraduationObtain', models.IntegerField()),
                ('GraduationSubject', models.CharField(max_length=50)),
                ('GraduationPercentage', models.FloatField(default='0.0')),
                ('GraduationGrades', models.CharField(max_length=5, null=True)),
                ('GraduationYear', models.CharField(max_length=20)),
                ('Matrics_Result', models.FileField(upload_to='media/', verbose_name='Matric Result')),
                ('Graduations_result', models.FileField(upload_to='media/', verbose_name='Graduations_result')),
                ('Intermediate_result', models.FileField(upload_to='media/', verbose_name='Intermediate Result')),
                ('Image', models.ImageField(upload_to='media/images')),
                ('Qualify', models.CharField(choices=[{'PHD', 'phd'}, {'Master', 'master'}, {'bachlor', 'Bachlor'}], max_length=10)),
                ('Speclization', models.CharField(choices=[{'please select', 'Please Select'}, {'Networking', 'networking'}, {'database', 'Database'}, {'programming', 'Programming'}], max_length=30)),
                ('Experience', models.FileField(default='Upload your CV', upload_to='media/CVs')),
                ('Master_Specialization', models.CharField(choices=[{'please select', 'Please Select'}, {'cs', 'CS'}, {'SE', 'se'}, {'it', 'IT'}], max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
