# Generated by Django 3.0.5 on 2020-04-29 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserViews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Experience',
            field=models.FileField(default='Upload your CV', upload_to='CVs/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='Graduations_result',
            field=models.FileField(upload_to='Results/', verbose_name='Graduations_result'),
        ),
        migrations.AlterField(
            model_name='application',
            name='Image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='Intermediate_result',
            field=models.FileField(upload_to='Results/', verbose_name='Intermediate Result'),
        ),
        migrations.AlterField(
            model_name='application',
            name='Matrics_Result',
            field=models.FileField(upload_to='Results/', verbose_name='Matric Result'),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
