# Generated by Django 3.0.5 on 2020-05-07 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InterviewPanel', '0002_auto_20200508_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='choice1',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='choice2',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='choice3',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='choice4',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='answers_at_end',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='random_order',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='roll_out',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='slug',
        ),
        migrations.AddField(
            model_name='quiz',
            name='Count',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InterviewPanel.Questions')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InterviewPanel.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='correct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InterviewPanel.Questions')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InterviewPanel.Questions')),
            ],
        ),
    ]
