# Generated by Django 3.0.5 on 2020-05-07 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InterviewPanel', '0003_auto_20200508_0401'),
    ]

    operations = [
        migrations.DeleteModel(
            name='correct',
        ),
    ]
