# Generated by Django 3.0.5 on 2020-05-14 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InterviewPanel', '0008_auto_20200511_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='InterviewPanel.Quiz'),
            preserve_default=False,
        ),
    ]
