# Generated by Django 3.0.5 on 2020-05-10 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InterviewPannel', '0005_auto_20200511_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='Count',
        ),
    ]
