# Generated by Django 3.0.5 on 2020-05-10 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InterviewPannel', '0006_remove_quiz_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='questions_ptr',
        ),
        migrations.AddField(
            model_name='answers',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InterviewPannel.Questions'),
        ),
        migrations.RemoveField(
            model_name='questions',
            name='quiz',
        ),
        migrations.AddField(
            model_name='questions',
            name='quiz',
            field=models.ManyToManyField(to='InterviewPannel.Quiz', verbose_name='Quiz'),
        ),
    ]
