# Generated by Django 3.0.5 on 2020-05-10 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InterviewPannel', '0007_auto_20200511_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InterviewPannel.Quiz'),
        ),
    ]
